apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      testapp: web
  template:
    metadata:
      labels:
       testapp: web
    spec:
      containers:
      - name: testapp
        image: lighteagle/testapp:latest
        env:
        - name: redisHost
          value: redishost
---
apiVersion: v1
kind: Service
metadata:
  name: testapp-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    testapp: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
